---
- name: installing tomcat 10 on ubuntu server 22.0
  hosts: appserver
  become: yes    
  tasks:
    - name: install java 11 on ubuntu
      ansible.builtin.package:
        name: "{{java_package_name}}"
        state: present