---
- name: installing tomcat 10 on ubuntu server 22.0
  hosts: appserver
  become: yes    
  tasks:
    - name: update th packages in ubuntu
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: install java 11 on ubuntu
      ansible.builtin.package:
        name: "{{java_package_name}}"
        state: present