all:
  children:
    appservers:
      hosts:
        172.31.2.132:
          java_package_name: openjdk-11-jdk
        172.31.5.253:
          java_package_name: java-1.8.0-openjdk-devel
          
        