--- 
- name: installing tomcat server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: installing the openjdk11
      ansible.builtin.package:
        name: "{{ java_package_name}}"
        state: present
     
        