---
- name: installing tomcat server in ubntu&centos
  hosts: appservers
  become: yes
  tasks:
    - name: installing openjdk11
      ansible.builtin.package: 
        name: "{{ java_package_name }}"
        state: present
        