---
- name: installing tomcat 10 on ubuntu server 22.0
  hosts: all
  become: yes
  tasks:
    - name: install java 11 on ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: true
        state: present
    - name: creating a tomcat user-group  
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: creating the tomcat user 
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        create_home: true
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download tomcat 10.0..27
      ansible.builtin.unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz  
        remote_src: true
        dest: /opt/tomcat
    - name: create a symbolic link 
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.0.27
        dest: /opt/tomcat/latest
        owner: tomcat
        group: tomcat 
        state: link
    - name: change the ownership 
      ansible.builtin.file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: true
        state: directory
    - name: add executable permissions to shell file
      ansible.builtin.command:
        cmd: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: create a tomcat.service file 
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload the tomcat
      ansible.builtin.systemd:
        name: tomcat
        daemon_reload: true
        enabled: true
        state: restarted
    - name: copy the user.xml file
      ansible.builtin.copy:
        src: tomcat.user.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: tomcat
        group: tomcat





