---
- name: installing tomcat 10 on ubuntu server 22.0
  hosts: all
  become: yes
  vars: 
    java_package_name: openjdk-11-jdk
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_shell: /bin/false
    tomcat_home: /opt/tomcat
    tomcat_service: tomcat.service
    tomcat_version: "10.0.27"
    major_version: "10"
  tasks:
    - name: install java 11 on ubuntu
      ansible.builtin.apt:
        name: "{{java_package_name}}"
        update_cache: true
        state: present
    - name: creating a tomcat user-group  
      ansible.builtin.group:
        name: "{{tomcat_user}}"
        state: present
    - name: creating the tomcat user 
      ansible.builtin.user:
        name: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
        create_home: true
        home: "{{tomcat_home}}"
        shell: "{{tomcat_shell}}"
        state: present
    - name: download and untar tomcat 10.0..27
      ansible.builtin.unarchive:
        src: "https://dlcdn.apache.org/tomcat/tomcat-{{major_version}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz"  
        remote_src: true
        dest: "{{tomcat_home}}"
    - name: create a symbolic link 
      ansible.builtin.file:
        src: "{{tomcat_home}}/apache-tomcat-{{tomcat_version}}"
        dest: /opt/tomcat/latest
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}" 
        state: link
    - name: change the ownership 
      ansible.builtin.file:
        path: "{{tomcat_home}}"
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
        recurse: true
        state: directory
    - name: add executable permissions to shell file
      ansible.builtin.command:
        cmd: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: create a tomcat.service file 
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
    - name: reload the deamon and start tomcat
      ansible.builtin.systemd:
        name: "{{tomcat_user}}"
        daemon_reload: true
        enabled: true
        state: started
    - name: copy the user.xml file
      ansible.builtin.copy:
        src: tomcat-user.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
    - name: copy the manager context file 
      ansible.builtin.copy:
        src: context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
    - name: copy the hostmanager context file 
      ansible.builtin.copy:
        src: hostmanager-context.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: "{{tomcat_user}}"
        group: "{{tomcat_group}}"
    - name: deamon reload and start tomcat 
      ansible.builtin.systemd:
        name: "{{tomcat_service}}"
        state: restarted

