---
- name: installing utilities softwared on localhost
  hosts: local
  tasks:
    - name: installing utilities softwares
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ packages}}"
    - name: debig other variables 
      ansible.builtin.debug:
        var: job
