---
- name: installing utilities softwared on localhost
  hosts: all 
  tasks:
    - name: installing utilities softwares
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop:
        - git 
        - tree 
        - nano 
        - net-tools
