---
- name: installing utilities softwared on localhost
  hosts: local
  tasks:
    - name: installing utilities softwares
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      become: yes
      loop: "{{ packages}}"
    - name: debig other variables 
      ansible.builtin.debug:
        var: Job
    - name: special variables in ansible 
      ansible.builtin.debug:
        var: inventory_dir
    - name: name of the inventory file 
      ansible.builtin.debug:
        var: inventory_file
    - name: user of ansible
      ansible.builtin.debug:
        var: ansible_user
    - name: copying some dynamic values to file 
      ansible.builtin.template:
        src: info.txt.j2
        dest: /tmp/info.txt
        