---
- name: installing utilities softwared on localhost
  hosts: all 
  tasks:
    - name: installing utilities softwares
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      become: yes
