---
- name: installing tomcat server on upuntu&centos
  hosts: all
  become: yes
  vars:
    - package_name: apache2
  tasks:
    - name: installing apache2 on ubuntu
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
      notify:
        - enable and restart apache2
    - name: installing apache on centos
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts['distribution'] == "CentOs"
      notify:
        - enable and restart httpd
    - name: installing php modules
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
      when: ansible_facts['distribution'] == "Ubuntu"
      notify:
        - enable and restart httpd
    - name: installing php modules in centos
      ansible.builtin.yum:
        name: 
          - php
          - php-mysqlnd
        state: present
      when: ansible_facts['distribution'] == "CentOs"
      notify:
        - enable and restart httpd
    - name: copy info.php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
  handlers:
    - name: enable and restart apache2
      ansible.builtin.systemd:
        name: apache2
        deamon_reload: true
        enabled: true
        state: restarted
    - name: enable and restart httpd
      ansible.builtin.systemd:
        name: httpd
        deamon_reload: true
        enabled: true
        state: restarted

